image:
- Visual Studio 2019
- Ubuntu
stack: node 10
environment:
  nodejs_version: "10"
  GITHUB_TOKEN:
    secure: t1s7bP+lo6z4Gv+F0J2pvD4KY2nzgdtOtrz/eN3Q41XgoV4+GnBtuY2oHQdQJ1nH
cache:
- '%LOCALAPPDATA%\Yarn'
- '$HOME/.yarn'
- '%LOCALAPPDATA%\electron\Cache'
- '$HOME/.cache/electron'
- '$HOME/Library/Caches/electron'
- node_modules
branches:
  only:
  - forge6-flatpak
  - master
  - /^v\d\.\d\.\d/
install:
- ps: |
    if ($isWindows) {
      Install-Product node $env:nodejs_version
    } elseif ($isLinux) {
      sudo apt-get update
      sudo apt-get install --yes --no-install-recommends rpm dpkg fakeroot
    } else {
      brew install yarn
    }
- sh: ci/platform_setup.sh
- yarn

test_script:
- node --version
- yarn --version
- yarn lint
- cmd: if %APPVEYOR_REPO_TAG% EQU false yarn make
- sh: if test "$APPVEYOR_REPO_TAG" = "false"; then yarn make; fi

build_script:
- cmd: IF %APPVEYOR_REPO_TAG% EQU true yarn publish
- sh: if test "$APPVEYOR_REPO_TAG" = "true"; then yarn publish; fi

artifacts:
- path: out/make/**/*
  name: Distributables
